# Generated by Django 5.2.6 on 2026-08-18 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('internal_length', models.DecimalField(decimal_places=2, help_text='cm', max_digits=10)),
                ('internal_width', models.DecimalField(decimal_places=2, help_text='cm', max_digits=10)),
                ('internal_height', models.DecimalField(decimal_places=2, help_text='cm', max_digits=10)),
                ('max_weight', models.DecimalField(decimal_places=3, help_text='kg', max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length', models.DecimalField(decimal_places=2, help_text='cm', max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, help_text='cm', max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, help_text='cm', max_digits=10)),
                ('weight', models.DecimalField(decimal_places=3, help_text='kg', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boxing.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='boxing.product')),
            ],
        ),
    ]
