# Generated by Django 5.2.6 on 2026-08-18 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='box',
            name='internal_height',
            field=models.DecimalField(decimal_places=2, help_text='cm', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='box',
            name='internal_length',
            field=models.DecimalField(decimal_places=2, help_text='cm', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='box',
            name='internal_width',
            field=models.DecimalField(decimal_places=2, help_text='cm', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='box',
            name='max_weight',
            field=models.DecimalField(decimal_places=3, help_text='kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='cm', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.DecimalField(decimal_places=2, help_text='cm', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, help_text='kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=2, help_text='cm', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
